### ISSUE TITLE
Job submissions with qss to IBM QPU end in Internal Server Error

### ISSUE THREAD

**Issue by vietphamngoc** [Infleqtion/client-superstaq#1033]
### What is happening?

When submitting circuits to an IBM backend, an ISE is returned. However the circuit is submitted and run on the backend as it appears on the IBM Quantum dashboard.

### How can we reproduce the issue?

```
provider = qss.SuperstaqProvider(ibmq_token=<API_KEY>, ibmq_channel="ibm_quantum")
backend = provider.get_backend('ibmq_kyoto_qpu')
qc = qiskit.QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()
compiler_output = backend.compile(qc)
circ = compiler_output.circuit
job = backend.run(circ, shots=1000)
job.result()
```
This results in:
![image](https://github.com/user-attachments/assets/e5909bda-790d-4456-afaf-59a6034ec5ff)

### What should happen?

This code should return the results of the submitted job.

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 0.5.24
- **Operating system**: 
- **Python version**: 3.11.7
- **Any other relevant dependencies**: 

### Any additional context?

I tried changing the values for `timeout` and `wait` in `job.result()` but still got the error.

**Comment by vtomole** [comment]
IBM is returning a job status that we don't handle. 

```python
 assert status in [
            "INITIALIZING",
            "VALIDATING",
            "QUEUED",
            "RUNNING",
            "DONE",
            "CANCELLED",
            "ERROR",
        ]
```

Adding it should fix this.

**Comment by vietphamngoc** [comment]
Thanks!
