### ISSUE TITLE
Change return types of `qiskit_superstaq.custom_gates` `__array__` methods

### ISSUE THREAD

**Issue by pgoiporia** [Infleqtion/client-superstaq#1045]
```suggestion
    def __array__(self, dtype: type | None = None) -> npt.NDArray[np.complex_]:
```
(this should be fixed for all the existing gates too)

_Originally posted by @richrines1 in https://github.com/Infleqtion/client-superstaq/pull/1044#discussion_r1735395924_

**Comment by bharat-thotakura** [comment]
Seems like a sub-issue of https://github.com/Infleqtion/client-superstaq/issues/94
