### ISSUE TITLE
QCVV sample repr fails if any component hasn't been generated yet

### ISSUE THREAD

**Issue by richrines1** [Infleqtion/client-superstaq#1071]
### What is happening?

`print(experiment.samples)` fails for qcvv experiments if any sample hasn't been both run and compiled, because `repr(sample)` will try to access missing attributes. this is pretty annoying when working in a python shell, which tries to print the repr if i just enter e.g. `experiment.samples[0]`

i think the easy (and imo best?) fix would be to have the missing attributes default to None instead of making them [`field`s with `init=False`](https://github.com/Infleqtion/client-superstaq/blob/ca80aad0c8bc72ddc4756c9d70673aef98944c59/supermarq-benchmarks/supermarq/qcvv/base_experiment.py#L40).

### How can we reproduce the issue?

```python
exp = supermarq.qcvv.IRB()
exp.prepare_experiment(2, [2])
print(exp.samples)  # AttributeError: 'Sample' object has no attribute 'probabilities'

exp.run_with_simulator()
print(exp.samples)  # AttributeError: 'Sample' object has no attribute 'compiled_circuit'
```

### What should happen?

i should be able to print the samples, even if they're not ready yet

### Environment

- **client-superstaq version**: 0.5.27
- **Python version**: 3.12

**Comment by cdbf1** [comment]
This is something that had been bugging me a bit too, I just hadn't gotten round to fixing so thanks for forcing me to actually sort it!
