### ISSUE TITLE
`supermarq/qcvv/irb_test.py::test_random_two_qubit_clifford` test flakes

### ISSUE THREAD

**Issue by bharat-thotakura** [Infleqtion/client-superstaq#1084]
The initial deploy for [`v0.5.28`](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937) failed twice due to a pytest & coverage check flake: [Attempt #1 run](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31042699696), [Attempt #2 run](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/attempts/2). See full details below:

<details>
 <summary>
run_checks / Pytest and Coverage check (3.10) failure</summary>
Run checks/coverage_.py
============================= test session starts ==============================
platform linux -- Python 3.10.15, pytest-8.3.3, pluggy-1.5.0
Using --randomly-seed=3333475222
rootdir: /home/runner/work/client-superstaq/client-superstaq
configfile: pyproject.toml
plugins: socket-0.7.0, randomly-3.15.0, xdist-3.6.1, nbmake-1.5.4, cov-5.0.0
collected 561 items

qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py ................ [  2%]
......                                                                   [  3%]
supermarq-benchmarks/supermarq/plotting_test.py ....                     [  4%]
supermarq-benchmarks/supermarq/benchmark_test.py ..                      [  4%]
general-superstaq/general_superstaq/resource_estimate_test.py .          [  5%]
supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py ............ [  7%]
.....................                                                    [ [11](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31042699696#step:6:12)%]
supermarq-benchmarks/supermarq/converters_test.py ..                     [ 11%]
qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py ............ [ 13%]
....                                                                     [ 14%]
qiskit-superstaq/qiskit_superstaq/validation_test.py .                   [ 14%]
qiskit-superstaq/qiskit_superstaq/serialization_test.py ................ [ 17%]
........................................................................ [ 30%]
..................................................                       [ 39%]
supermarq-benchmarks/supermarq/benchmarks/qaoa_fermionic_swap_proxy_test.py . [ 39%]
.                                                                        [ 39%]
cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py .................. [ 42%]
.................                                                        [ 45%]
cirq-superstaq/cirq_superstaq/validation_test.py ..                      [ 45%]
cirq-superstaq/cirq_superstaq/job_test.py .........................      [ 50%]
supermarq-benchmarks/supermarq/benchmarks/phase_code_test.py ...         [ 50%]
cirq-superstaq/cirq_superstaq/compiler_output_test.py .......s..         [ 52%]
supermarq-benchmarks/supermarq/benchmarks/bit_code_test.py ...           [ 53%]
supermarq-benchmarks/supermarq/benchmarks/mermin_bell_test.py ..         [ 53%]
general-superstaq/general_superstaq/validation_test.py ....              [ 54%]
general-superstaq/general_superstaq/serialization_test.py .              [ 54%]
cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py .................. [ 57%]
....................................                                     [ 64%]
supermarq-benchmarks/supermarq/benchmarks/vqe_proxy_test.py ..           [ 64%]
qiskit-superstaq/qiskit_superstaq/compiler_output_test.py ......s...     [ 66%]
qiskit-superstaq/qiskit_superstaq/custom_gates_test.py ..........        [ 68%]
cirq-superstaq/cirq_superstaq/_version_test.py .                         [ 68%]
general-superstaq/general_superstaq/_version_test.py .                   [ 68%]
supermarq-benchmarks/supermarq/qcvv/xeb_test.py .......                  [ 69%]
supermarq-benchmarks/supermarq/features_test.py ......                   [ 70%]
cirq-superstaq/cirq_superstaq/serialization_test.py .                    [ 70%]
general-superstaq/general_superstaq/superstaq_client_test.py ........... [ 72%]
.............................................                            [ 80%]
supermarq-benchmarks/supermarq/qcvv/irb_test.py ........F...             [ 83%]
qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py ........... [ 85%]
............                                                             [ 87%]
general-superstaq/general_superstaq/superstaq_exceptions_test.py ....    [ 87%]
qiskit-superstaq/qiskit_superstaq/_version_test.py .                     [ 88%]
cirq-superstaq/cirq_superstaq/service_test.py .......................... [ 92%]
..........                                                               [ 94%]
supermarq-benchmarks/supermarq/benchmarks/hamiltonian_simulation_test.py . [ 94%]
.                                                                        [ 94%]
general-superstaq/general_superstaq/service_test.py ..............       [ 97%]
supermarq-benchmarks/supermarq/benchmarks/ghz_test.py ............       [ 99%]
supermarq-benchmarks/supermarq/_version_test.py .                        [ 99%]
supermarq-benchmarks/supermarq/benchmarks/qaoa_vanilla_proxy_test.py ..  [100%]

=================================== FAILURES ===================================
________________________ test_random_two_qubit_clifford ________________________

    def test_random_two_qubit_clifford() -> None:
        with patch("numpy.random.default_rng", side_effect=np.random.default_rng) as rng:
            rng.return_value.integers.side_effect = range(20)
            exp = IRB()
    
            gates: set[cirq.Gate] = set()
            for _ in range(20):
                gate = exp.random_two_qubit_clifford()
                assert isinstance(gate, cirq.ops.CliffordGate)
                assert gate.num_qubits() == 2
>               assert gate not in gates
E               assert Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Z0   | - Y0X1\n+ Z0Z1 | +   X1\n not in {Clifford Gate with Tableau:\n stable | destable\n-------+----------\n+ Z0Z1 | - Z0Y1\n+ Z0   | + X0X1\n, Clifford Gate wit... Z1 | + Y0X1\n, Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Y0X1 | - Z0X1\n+ X0Z1 | + X0Y1\n, ...}

supermarq-benchmarks/supermarq/qcvv/irb_test.py:94: AssertionError
----------------------------- Captured stdout call -----------------------------
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[False], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[False], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[False], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[False], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[True], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.dtype('bool')), xs=np.array([[True], [False]], dtype=np.dtype('bool')),zs=np.array([[True], [True]], dtype=np.dtype('bool')), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.dtype('bool')), xs=np.array([[False], [True]], dtype=np.dtype('bool')),zs=np.array([[True], [False]], dtype=np.dtype('bool')), initial_state=0))
=========================== short test summary info ============================
FAILED supermarq-benchmarks/supermarq/qcvv/irb_test.py::test_random_two_qubit_clifford - assert Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Z0   | - Y0X1\n+ Z0Z1 | +   X1\n not in {Clifford Gate with Tableau:\n stable | destable\n-------+----------\n+ Z0Z1 | - Z0Y1\n+ Z0   | + X0X1\n, Clifford Gate wit... Z1 | + Y0X1\n, Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Y0X1 | - Z0X1\n+ X0Z1 | + X0Y1\n, ...}
============= 1 failed, 558 passed, 2 skipped in 72.96s (0:01:[12](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31042699696#step:6:13)) ==============
Name    Stmts   Miss    Cover   Missing
---------------------------------------
TOTAL    8444      0  100.00%

90 files skipped due to complete coverage.
TEST FAILURE!
Error: Process completed with exit code 1.
</details>

<details>
 <summary>
run_checks / Pytest and Coverage check (3.8) failure</summary>
Run checks/coverage_.py
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.3.3, pluggy-1.5.0
Using --randomly-seed=1369402718
rootdir: /home/runner/work/client-superstaq/client-superstaq
configfile: pyproject.toml
plugins: socket-0.7.0, randomly-3.15.0, xdist-3.6.1, nbmake-1.5.4, cov-5.0.0
collected 561 items

cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py .................. [  3%]
....................................                                     [  9%]
general-superstaq/general_superstaq/_version_test.py .                   [  9%]
supermarq-benchmarks/supermarq/benchmarks/mermin_bell_test.py ..         [ 10%]
qiskit-superstaq/qiskit_superstaq/_version_test.py .                     [ 10%]
supermarq-benchmarks/supermarq/plotting_test.py ....                     [ [11](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31043342754#step:6:12)%]
general-superstaq/general_superstaq/serialization_test.py .              [ 11%]
supermarq-benchmarks/supermarq/qcvv/xeb_test.py .......                  [ [12](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31043342754#step:6:13)%]
supermarq-benchmarks/supermarq/qcvv/irb_test.py ...F........             [ 14%]
qiskit-superstaq/qiskit_superstaq/validation_test.py .                   [ [14](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31043342754#step:6:15)%]
qiskit-superstaq/qiskit_superstaq/custom_gates_test.py ..........        [ 16%]
supermarq-benchmarks/supermarq/benchmark_test.py ..                      [ 16%]
supermarq-benchmarks/supermarq/benchmarks/hamiltonian_simulation_test.py . [ 17%]
.                                                                        [ 17%]
supermarq-benchmarks/supermarq/_version_test.py .                        [ 17%]
general-superstaq/general_superstaq/validation_test.py ....              [ 18%]
general-superstaq/general_superstaq/resource_estimate_test.py .          [ 18%]
cirq-superstaq/cirq_superstaq/_version_test.py .                         [ 18%]
cirq-superstaq/cirq_superstaq/serialization_test.py .                    [ 18%]
supermarq-benchmarks/supermarq/benchmarks/ghz_test.py ............       [ 20%]
cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py .................. [ 24%]
.................                                                        [ 27%]
qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py ........... [ 29%]
............                                                             [ 31%]
general-superstaq/general_superstaq/superstaq_exceptions_test.py ....    [ 31%]
supermarq-benchmarks/supermarq/benchmarks/bit_code_test.py ...           [ 32%]
supermarq-benchmarks/supermarq/benchmarks/qaoa_vanilla_proxy_test.py ..  [ 32%]
cirq-superstaq/cirq_superstaq/service_test.py .......................... [ 37%]
..........                                                               [ 39%]
supermarq-benchmarks/supermarq/benchmarks/phase_code_test.py ...         [ 39%]
general-superstaq/general_superstaq/superstaq_client_test.py ........... [ 41%]
.............................................                            [ 49%]
qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py ............ [ 51%]
....                                                                     [ 52%]
supermarq-benchmarks/supermarq/benchmarks/qaoa_fermionic_swap_proxy_test.py . [ 52%]
.                                                                        [ 52%]
cirq-superstaq/cirq_superstaq/compiler_output_test.py ..s.......         [ 54%]
qiskit-superstaq/qiskit_superstaq/serialization_test.py ................ [ 57%]
........................................................................ [ 70%]
..................................................                       [ 79%]
cirq-superstaq/cirq_superstaq/job_test.py .........................      [ 83%]
general-superstaq/general_superstaq/service_test.py ..............       [ 86%]
cirq-superstaq/cirq_superstaq/validation_test.py ..                      [ 86%]
qiskit-superstaq/qiskit_superstaq/compiler_output_test.py ....s.....     [ 88%]
supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py ............ [ 90%]
.....................                                                    [ 94%]
supermarq-benchmarks/supermarq/converters_test.py ..                     [ 94%]
qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py ................ [ 97%]
......                                                                   [ 98%]
supermarq-benchmarks/supermarq/benchmarks/vqe_proxy_test.py ..           [ 98%]
supermarq-benchmarks/supermarq/features_test.py ......                   [100%]

=================================== FAILURES ===================================
________________________ test_random_two_qubit_clifford ________________________

    def test_random_two_qubit_clifford() -> None:
        with patch("numpy.random.default_rng", side_effect=np.random.default_rng) as rng:
            rng.return_value.integers.side_effect = range(20)
            exp = IRB()
    
            gates: set[cirq.Gate] = set()
            for _ in range(20):
                gate = exp.random_two_qubit_clifford()
                assert isinstance(gate, cirq.ops.CliffordGate)
                assert gate.num_qubits() == 2
>               assert gate not in gates
E               assert Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- X0X1 | - X0Y1\n- Y0Z1 | + Z0Z1\n not in {Clifford Gate with Tableau:\n stable | destable\n-------+----------\n-   X1 | + X0Z1\n+ Z0X1 | + Y0X1\n, Clifford Gate wit...0X1 | + X0Y1\n, Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Y0   | - X0X1\n+ Y0Z1 | + Y0Y1\n, ...}

supermarq-benchmarks/supermarq/qcvv/irb_test.py:94: AssertionError
----------------------------- Captured stdout call -----------------------------
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [False]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [False]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[True], [False]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [False]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[True], [False]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [True]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([True, False], dtype=np.bool), xs=np.array([[False], [True]], dtype=np.bool),zs=np.array([[True], [True]], dtype=np.bool), initial_state=0))
cirq.CliffordGate.from_clifford_tableau(cirq.CliffordTableau(1,rs=np.array([False, True], dtype=np.bool), xs=np.array([[True], [False]], dtype=np.bool),zs=np.array([[False], [True]], dtype=np.bool), initial_state=0))
=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/__init__.py:47
  /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qiskit/__init__.py:47: DeprecationWarning: Using Qiskit with Python 3.8 is deprecated as of the 1.1.0 release. Support for running Qiskit with Python 3.8 will be removed in the 1.3.0 release, which coincides with when Python 3.8 goes end of life.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED supermarq-benchmarks/supermarq/qcvv/irb_test.py::test_random_two_qubit_clifford - assert Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- X0X1 | - X0Y1\n- Y0Z1 | + Z0Z1\n not in {Clifford Gate with Tableau:\n stable | destable\n-------+----------\n-   X1 | + X0Z1\n+ Z0X1 | + Y0X1\n, Clifford Gate wit...0X1 | + X0Y1\n, Clifford Gate with Tableau:\n stable | destable\n-------+----------\n- Y0   | - X0X1\n+ Y0Z1 | + Y0Y1\n, ...}
======== 1 failed, 558 passed, 2 skipped, 1 warning in 95.42s (0:01:35) ========
Name    Stmts   Miss    Cover   Missing
---------------------------------------
TOTAL    84[15](https://github.com/Infleqtion/client-superstaq/actions/runs/11167141937/job/31043342754#step:6:16)      0  100.00%

90 files skipped due to complete coverage.
TEST FAILURE!
Error: Process completed with exit code 1.
</details>

**Comment by cdbf1** [comment]
Thanks for highlighting, definitely a dodgy test!
