### ISSUE TITLE
Find a simpler way to send QUBO to server

### ISSUE THREAD

**Issue by singular-value** [Infleqtion/client-superstaq#143]
https://github.com/SupertechLabs/applications-superstaq/blob/374db4248901c6ebef3773a388d00bf833bb869b/applications_superstaq/qubo.py#L19

**Comment by vtomole** [comment]
This is the simplest way to send QUBOs to the server. The keys of the QUBOs are tuples which are not valid JSON  keys hence why `convert_qubo_to_model` converts them to strings before sending them to the server. Serilaizing using `pickle` or the other ways @richrines1 has suggested are not simple. They are more likely to break this functionality in the future.

**Comment by richrines1** [comment]
@vtomole what's wrong with `list(qubo.items())`?

**Comment by vtomole** [comment]
> what's wrong with list(qubo.items())?

Maybe.

@dhirpalshah Please try this out.
