### ISSUE TITLE
Turn `SupermarQ.ipynb` into `submit.py` and `score.py`

### ISSUE THREAD

**Issue by teaguetomesh** [Infleqtion/client-superstaq#16]
The main functions performed by `SupermarQ.ipynb` are:

Create a `service` object
Submit benchmarks through `cirq-superstaq`
Collect benchmark results and compute the score

We'll split these functionalities up into two separate files for now

**Comment by vtomole** [comment]
Notebook was split into `.py` files and `SupermarQ.ipynb` doesn't exist anymore.
