### ISSUE TITLE
Improvements to `uchicago_workshop.ipynb`

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#189]
- [ ] Construct circuits in the notebook that display the SWAP circuit decomposed into the `[CR, R_{phi}(theta)]` gateset. This makes it easier to see exactly which single qubits gates can be cancelled out.
- [ ] Go into depth about how exactly the  single qubit gates are cancelled out. What identities are used for optimizing?
- [ ]  Explain how to interpret the pulse diagrams that qiskit displays. Matter of fact, show how to reconstruct the circuit using the pulse diagrams to show that the optimizations that are done to SWAP are in the lens of "gates".
- [ ] Go into depth about what exactly the CR gate is. Explain polarity.

**Comment by stephanielee9** [comment]
Close when @vtomole deletes notebook from main
