### ISSUE TITLE
SuperstaQ can't run circuits on `ibmq_mumbai_qpu` because compiler fails

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#215]
`out = service.ibmq_compile(circuit, target="ibmq_mumbai_qpu")` throws `SuperstaQException: Status code: 400, Message: 'Non-retriable error making request to SuperstaQ API, You can't compile a circuit with this device. Please try another device.'` 

Close this issue once this is fixed for other devices as well.  There needs to be a design that accounts for compiling for gate based devices in `ibmq_compile`. Maybe add a pulse flag to it.

**Comment by stephanielee9** [comment]
@vtomole check ORNL IBM access

**Comment by vtomole** [comment]
We don't have access to IBM via ORNL. Moving to long term until we do.

**Comment by richrines1** [comment]
if we want to support user tokens we'll have to be able to support devices we don't have (unpaid) access to

**Comment by vtomole** [comment]
How will we test said devices if we don't access to them?

**Comment by richrines1** [comment]
actually nvm, given this

> Also note that IBM may be phasing our direct CX entirely ([link](https://teams.microsoft.com/l/message/19:1f7bc7c7410046d8a2d4efe221e957ee@thread.tacv2/1673190227316?tenantId=880a2c20-cd2a-4317-9b16-f4860862e909&groupId=d6f5f101-cbec-495f-85c2-4facc97649be&parentMessageId=1673190227316&teamName=CQ-Chicago&channelName=industry_observations&createdTime=1673190227316&allowXTenantAccess=false))

we probably shouldn't worry about this one unless someone needs it. imo the more general question about testing/supporting other devices maybe warrants a discussion irl at some point though

**Comment by vtomole** [comment]
> more general question about testing/supporting other devices maybe warrants a discussion irl at some point though

CC @stephanielee9  for dev meeting.
