### ISSUE TITLE
Submitting a job in testing

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/client-superstaq#266]
SupertechLabs/superstaq-client#261 has been an issue for a while, i.e., our tests didn't catch that `job.repetitions()` fails. But to really test that, we would need an integration test that submits a job, e.g., to `ibmq_qasm_simulator`. Do we want to do something like that, or is there another option? (@richrines1 interested to hear your thoughts)

**Comment by stephanielee9** [comment]
Confirm that we do have integration tests before we submit jobs - we do have them for cirq-superstaq, not qiskit-superstaq

**Comment by stephanielee9** [comment]
^confirmed by @vtomole
