### ISSUE TITLE
Make `pytest` skip notebook check if no AQT configs

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/client-superstaq#373]
### What is happening?

Update pytest notebook check with a skip-if for the `aqt.ipynb` notebook if there are no AQT configs. This will allow dev clients to run the full pytest check without configs.

Also, we should upload the configs to `TEST_USER_TOKEN` and we should be using the `TEST_USER_TOKEN` instead of the SuperstaQ token for the check (see `ci.yml`).

### What are the current alternatives?

Let clients have configs access -- but I think this was discussed a while ago and decided against.

**Comment by stephanielee9** [comment]
Closed by https://github.com/Infleqtion/client-superstaq/pull/552
