### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#395]
Currently, repo is displaying readme from docs-superstaq. We'll need a new readme for clients that displays info on all the client submodules + interesting graphics, contact info, etc.

Good reference: https://github.com/AgnostiqHQ/covalent

**Comment by stephanielee9** [comment]
Temporary fix: https://github.com/SupertechLabs/client-superstaq/pull/406

**Comment by stephanielee9** [comment]
Update logo, demo GIF

**Comment by stephanielee9** [comment]
For code snippet GIFs: https://recoded.netlify.app/

**Comment by stephanielee9** [comment]
Decide on code snippet closer to release date

**Comment by stephanielee9** [comment]
make GIF as hello example
seeing pulses

**Comment by richrines1** [comment]
we should probably also update `general-superstaq/README.md` (which currently reads as if it's the top of the monorepo) 
![image](https://github.com/Infleqtion/client-superstaq/assets/85512171/4518a438-58d9-4364-b995-9d3957c86643)

**Comment by stephanielee9** [comment]
Closed by https://github.com/Infleqtion/client-superstaq/pull/577, https://github.com/Infleqtion/client-superstaq/pull/568
