### ISSUE TITLE
Be able to print submitted circuits when submitting to Hilbert via css and qss

### ISSUE THREAD

**Issue by SalahedeenIssa** [Infleqtion/client-superstaq#441]
### What is happening?

Currently there doesn't seem to be a manner by which I can call the submitted or compiled circuits in the same way that I can call the job_id. We should try and implement this in css.Service()

**Comment by stephanielee9** [comment]
@SalahedeenIssa can you confirm if this is fixed and close this issue if so? Related PR: https://github.com/Infleqtion/client-superstaq/pull/605

**Comment by SalahedeenIssa** [comment]
Yep it works!
