### ISSUE TITLE
Can't submit circuits (with my token) using css

### ISSUE THREAD

**Issue by SalahedeenIssa** [Infleqtion/client-superstaq#442]
### What is happening?

For some reason, even after refreshing my token many times, I was getting the following error:

SuperstaQException: Status code: 400, Message: 'Non-retriable error making request to SuperstaQ API, Your CQ token is invalid. The token you are using has probably expired. Refresh it.' 

when attempting to run this code. 

However, when submitting using @vtomole 's SuperstaQ token, or just submitting through SuperstaQ directly, everything ran smoothly. 

### How can we reproduce the issue?

The script I ran was : 

```python
token = "token"

service = css.Service(token)

qubits = cirq.LineQubit.range(2)
circuit = cirq.Circuit(
    cirq.H(qubits[0]),
    cirq.CNOT(qubits[0], qubits[1]),
    cirq.measure(qubits[0]),
    cirq.measure(qubits[1]),
)

job_css = service.create_job(
    circuit=circuit, repetitions=100, target="cq_hilbert_simulator", options=options
)
result_css = job_css.counts()

print(f"Counts from cirq-superstaq submission: {result_css}")

```

### What should happen?

It should run the circuit on the Hilbert simulator, and print out the counts. 

### Environment

- **SuperstaQ version**: 0.3.33
- **general-superstaq version**: 
- **cirq-superstaq version**:  0.3.24
- **qiskit-superstaq version**: 
- **Operating system**: 
- **Python version**: 
- **Any other relevant dependencies**:

**Comment by stephanielee9** [comment]
@pgoiporia is looking into it

**Comment by pgoiporia** [comment]
It should work now @SalahedeenIssa

**Comment by SalahedeenIssa** [comment]
Works!
