### ISSUE TITLE
cq_compiler produces GR gate on one qubit in 16 qubit register

### ISSUE THREAD

**Issue by ColinCampbellCQ** [Infleqtion/client-superstaq#448]
### What is happening?

cq_compiler produces circuits that use GR gates on not all qubits

### How can we reproduce the issue?
```python
circuit1 = qiskit.QuantumCircuit(1, 1)
circuit1.h(0)
circuit1.measure(0, 0)
compiler_output = provider.cq_compile(circuit1)
```
observe that the GR gate operates on only one qubit instead of 16

### What should happen?

GR gate should apply to all qubits in the circuit instead of just one.

### Environment

- **SuperstaQ version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: '0.3.24'
- **Operating system**:  Windows
- **Python version**: 3.8
- **Any other relevant dependencies**: 

### Any additional context?

This issue is also an issue in the cloud service. This circuit will actually be accepted as a valid circuit in the cloud, even though it should not. I believe that issue also has a ticket, so when it gets fixed, the circuit produced by the compiler here will not work.

**Comment by ColinCampbellCQ** [comment]
1. The compiled circuit has 16 qubits. The original circuit (a single Hadamard gate with a single measurement) has one qubit.
2. On Hilbert GR only acts on all qubits in a circuit (not a subset). Qiskit allows someone to define a circuit where GR acts on a subset of qubits, as in the case of the compiled circuit), but that operation is not valid for Hilbert. It is one issue that Hilbert currently accepts circuits like this (cloud team), but it is another that the compiler may produce them.

**Comment by perlinm** [comment]
Clarifying / rewording question number 2: Have you seen SuperstaQ spit out a circuit that uses `k` qubits, but contains a GR that addresses only a strict subset of those `k`?

**Comment by ColinCampbellCQ** [comment]
No. I have only used the SuperstaQ compiler once in perhaps nearly a year and it was for this circuit.

**Comment by perlinm** [comment]
Cool, thanks.  In that case I suspect that SuperstaQ is simply making a Cirq circuit on the only qubit addressed by the circuit, and then not extending the GR onto all qubits when it converts into a Qiskit circuit that has a register containing all qubits on the device.

Should be an easy fix, thanks for catching it :slightly_smiling_face: 

@SalahedeenIssa would you be able to look into this?

**Comment by perlinm** [comment]
Request for consult @vtomole @richrines1 on how to deal with this.  There seem to be a couple of options, but it's ultimately a software design choice.  I can debrief offline.

**Comment by stephanielee9** [comment]
Rich and Victory to chat about this later today

**Comment by richrines1** [comment]
something @perlinm and i had discussed but i forgot to note here: when we fix this, we should also add something like a `.truncated_circuit(s)` attribute (to be computed client-side) to the compiler output, which would remove all otherwise-inactive qubits from any GR gate in the compiled circuit(s). among other things this would be useful for gate-level simulations

**Comment by stephanielee9** [comment]
not pressing because the hardware-side update that will make this necessary isn't particularly imminent

**Comment by perlinm** [comment]
@ColinCampbellCQ we should follow up on this issue sometime.  I have a few confusions, for example why one would want a GR gate on all qubits on Hilbert, rather than only on the qubits that are addressed by a circuit.

**Comment by ColinCampbellCQ** [comment]
In the example I gave, the GR gates should be acting on all the qubits because they address all the qubits. I ask for their measurements at the end, so the circuit does address all 24 qubits. Therefore there is a mismatch between the number of qubits being addressed in the circuit and the number of qubit addressed by the GR gate.

**Comment by ColinCampbellCQ** [comment]
Maybe it would be better to give a more concrete example. This is a circuit I can apparently submit to Hilbert
qc = QuantumCircuit(24)
qc.append(GR(8, pi/2, pi/2), range(8))
qc.append(GR(8, pi/2, 0), range(8, 16))
qc.append(GR(8, pi/2, pi/4), range(16, 24))
qc.measure_all()
job = hilbert.run(qc, shots=100, verbatim=True, method="dry-run")

I think this circuit should be rejected.

**Comment by SalahedeenIssa** [comment]
@ColinCampbellCQ @perlinm @richrines1 there is ongoing discussion on whether we should have the GR Gates touch each qubit in a circuit, or touch each qubit in a device. For example, if we choose the latter, then initializing a device with grid_shape = (2,2), and then creating a circuit with 3 qubits would cause an error upon compilation, as the GR would only touch 3 qubits and not 4. What do you guys think?

**Comment by richrines1** [comment]
> initializing a device with grid_shape = (2,2), and then creating a circuit with 3 qubits would cause an error upon compilation

why? we can/should always extend the GR gates to cover the rest of the device's qubits; we don't care what actually happens to them

**Comment by SalahedeenIssa** [comment]
So maybe we could set it so that GR gates have to touch all qubits in a device, but if they don't we could manually extend the GRs to cover all qubits

**Comment by richrines1** [comment]
i think that would work, though it might be simpler to just pass `device._qubits` to the various functions in `cq/decompose.py` and use those qubits whenever we instantiate a GR gate (which shouldn't change anything about how the circuit affects the active qubits)

**Comment by SalahedeenIssa** [comment]
But if you create a circuit with only 3 qubits using qiskit, and a device with 4, wouldn't a GR gate on ```device._qubits``` create an error anyways?

**Comment by ColinCampbellCQ** [comment]
I agree with Rich that doing GR on all device qubits seems like the best way to go. It just makes sense to have the gates in the compiled circuit correspond directly to the gates the hardware is using. The only thing that has made me less resolute on this principle is the context of simulation. Sometimes I want to test submitting circuits to Hilbert using few qubits, but if I were to put the GR gates on all 24 qubits, the task ends up being much harder for methods like noise-sim and dry-run.
