### ISSUE TITLE
Make `dev-requirements.txt` a superset of `example-requirements.txt`

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#450]
The only difference between it and `dev-requirements.txt` is the `notebook` requirement; so just add the notebook requirement to `dev-requirements.txt`

**Comment by richrines1** [comment]
it just occurred to me - i think the reason we kept this separate was that it allows users to run the notebooks without installing everything in dev-requirements

**Comment by vtomole** [comment]
I've renamed this issue to be more appropriate to what we want to do. Instead of removing `example-requirements.txt`, change https://github.com/SupertechLabs/client-superstaq/blob/addc22a3ffb750d2757f7c10e9c2227f16c73c5a/cirq-superstaq/setup.py#L44 to ` extras_require={"dev": dev_requirements + example_requirements, "examples": example_requirements}`

**Comment by richrines1** [comment]
closed by #557
