### ISSUE TITLE
Open in Colab and Binder links don't work in readthedocs

### ISSUE THREAD

**Issue by singular-value** [Infleqtion/client-superstaq#525]
### What is happening?

Open in Colab and Binder links don't work in readthedocs

### How can we reproduce the issue?

E.g. the links in https://docs-superstaq.readthedocs.io/en/stable/get_started/basics.html don't work

### What should happen?

They should open correctly as they do here: https://github.com/SupertechLabs/client-superstaq/blob/main/docs/source/get_started/basics/basics_css.ipynb

### Environment

Latest

**Comment by singular-value** [comment]
This seems to be broken again. Will look.

**Comment by stephanielee9** [comment]
@singular-value Just want to make sure: are these the links on docs-superstaq.readthedocs.io or superstaq.readthedocs.io? I've kept the docs-superstaq project open in case we need to look back on it, but the new docs should be on superstaq.readthedocs.io

**Comment by singular-value** [comment]
Ah that was it! superstaq.readthedocs.io works

Thanks @stephanielee9
