### ISSUE TITLE
Add flag to indicate mid-circuit measurement support to `target_info()`

### ISSUE THREAD

**Issue by epelaaez** [Infleqtion/client-superstaq#550]
### What is happening?

When running Supermarq, there are some benchmarks that require mid-circuit measurements. It would be helpful to know if a backend supports mid-circuit measurements through `service.target_info()` so we don't try to submit invalid circuits. 

### What are the current alternatives?

Use a try-except block to catch when a circuit is invalid for a certain device.

**Comment by bharat-thotakura** [comment]
Note: with https://github.com/Infleqtion/server-superstaq/pull/2481, `css.Service().target_info()` now shows if an IBM backend supports mid-circuit measurements and conditional operations. Though, following https://github.com/Infleqtion/server-superstaq/issues/2481#issuecomment-1636507165, we're keeping this issue still open for its possible relevance for other targets.
