### ISSUE TITLE
Update docstrings in `client-superstaq`

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/client-superstaq#563]
### What is happening?

From Open-Beta week: "Update docstrings in client --> add docstrings to methods and classes (make sure there are no pragmas for disabling docstrings in clients)" ~(also do this server-side, unless that's already done?)~

- Remove `#pylint` from test functions and add a single `#pylint` at the top of each test file
- Update old docstrings
- Review @pgoiporia's docstring spreadsheet and confirm changes

### What are the current alternatives?

None.

### Any additional context?

None.

**Comment by vtomole** [comment]
Server-side updates are big enough to be it's own issue. I've re-titled this one to be more specific.

**Comment by bharat-thotakura** [comment]
@dowusu-antwi 

I think PR #565 should address the first bullet point and I am currently looking at files that require docstrings (I knew already for example that `ops/qubit_gates.py` requires it). Should we make a checklist here or do you have a suggestion on how we should proceed?

**Comment by dowusu-antwi** [comment]
Sounds good, thanks!

> Should we make a checklist here or do you have a suggestion on how we should proceed?

I think we can use the spreadsheet checklist Palash made (he mentioned it probably need updates).

**Comment by bharat-thotakura** [comment]
@dowusu-antwi, going through the Excel file, all docstrings look to be fairly complete after merging #503 & #513. Further updates imo would mostly be of the 'nit kind' and increased conformity to the dev guide at the moment.

**Comment by bharat-thotakura** [comment]
To keep track: 

> Remove #pylint from test functions and add a single #pylint at the top of each test file

Completed by https://github.com/Infleqtion/client-superstaq/pull/565 & https://github.com/Infleqtion/client-superstaq/pull/578

> Update old docstrings

Addressed by #585, #588, #589, #590, & #591.

> Review @pgoiporia's docstring spreadsheet and confirm changes

Done (spreadsheet also updated now). 

This issue can be closed imo from merging the PRs listed above.
