### ISSUE TITLE
`grid_shape` not working as I would expect

### ISSUE THREAD

**Issue by SalahedeenIssa** [Infleqtion/client-superstaq#582]
### What is happening?

The following script: 

```python
import cirq
import cirq_superstaq as css
service = css.Service()
qubits = cirq.LineQubit.range(16)
example_circuit = cirq.Circuit(cirq.H.on_each(*qubits))
new_compiler_output = service.cq_compile(example_circuit, options={"grid_shape": (4, 4)})
print(new_compiler_output.circuit)
```

Should produce an output where the 16 qubits acted upon are a 4x4 grid from (0,0) to (3,3). However, instead, the output is this:
```
(0, 0): ───RGate(0.5π, -0.5π)───Z───
           │
(0, 1): ───#2───────────────────Z───
           │
(0, 2): ───#3───────────────────Z───
           │
(0, 3): ───#4───────────────────Z───
           │
(0, 4): ───#5───────────────────Z───
           │
(0, 5): ───#6───────────────────Z───
           │
(1, 0): ───#7───────────────────Z───
           │
(1, 1): ───#8───────────────────Z───
           │
(1, 2): ───#9───────────────────Z───
           │
(1, 3): ───#10──────────────────Z───
           │
(1, 4): ───#11──────────────────Z───
           │
(1, 5): ───#12──────────────────Z───
           │
(2, 0): ───#13──────────────────Z───
           │
(2, 1): ───#14──────────────────Z───
           │
(2, 2): ───#15──────────────────Z───
           │
(2, 3): ───#16──────────────────Z───
```

Which acts on all 6 qubits of the first two rows, and then the first 4 qubits of the third row. The same thing happens when I set the grid shape to (2,2), even though there should be an error thrown. 

### How can we reproduce the issue?

The script above should reproduce the issue.

### What should happen?

The code should produce a circuit in the 4x4 shape, or an error when I try to run 16 qubits on a 2x2 grid. 

### Environment

- **Superstaq version**: 0.3.49
- **general-superstaq version**: 0.4.0
- **cirq-superstaq version**: 0.4.0
- **qiskit-superstaq version**: 0.4.0

**Comment by SalahedeenIssa** [comment]
@perlinm @ColinCampbellCQ @dowusu-antwi @vtomole

**Comment by SalahedeenIssa** [comment]
@perlinm that's what I initially thought as well, but when Colin said it fixed his problem I assumed that this would work regardless.

**Comment by perlinm** [comment]
Let's have the docs exclude `grid_shape` for now, but add it back once this issue is fixed:
![image](https://github.com/Infleqtion/client-superstaq/assets/567092/2467e192-f021-494a-af8c-e92de28a8250)

**Comment by perlinm** [comment]
Update: after [ss#2466](https://github.com/Infleqtion/server-superstaq/pull/2466), the correct way to pass `grid_shape` is now:
```python
new_compiler_output = service.cq_compile(example_circuit, grid_shape=(3, 3))

```

**Comment by perlinm** [comment]
Actually, @SalahedeenIssa once [ss#2466](https://github.com/Infleqtion/server-superstaq/pull/2466) is merged and we re-deploy server-superstaq, can you check whether this is still an issue?  I think it might be fixed.

If it is fixed, we should go ahead and update the docs as well.

**Comment by SalahedeenIssa** [comment]
@perlinm it still doesn't seem to be working for me...

**Comment by SalahedeenIssa** [comment]
Nevermind I mistyped it, it works! I'll go ahead and update the docs.
