### ISSUE TITLE
Hilbert jobs inaccessible after cloud token expiration

### ISSUE THREAD

**Issue by ColinCampbellCQ** [Infleqtion/client-superstaq#592]
### What is happening?

Jobs on Hilbert appear to become inaccessible after CQ cloud token expires (which happens frequently).

### How can we reproduce the issue?

```import qiskit_superstaq as qss
qss_provider = qss.SuperstaQProvider("valid access token")
with open(os.path.expanduser("~/.coldquanta/cq_auth.json"), "r") as file:
    data = json.load(file)
options = {"cq_token": data, 'compile': False, 'route': False}
!python -m coldquanta.qc_common_api.cq_authorize
cq_hil = qss_provider.get_backend("cq_hilbert_qpu")
qc = //any valid quantum circuit
job = backend.run(qc, shots=100, options=options)
jid = job.job_id()
result = job.result()
retrieved_job = qss_provider._client.get_job(jid) //should be a dictionary
// wait for token to expire (does not take long)
retrieved_job_again = qss_provider._client.get_job(jid)  //should throw an error for expired CQ access token
```

### What should happen?

Either the token should not expire, or I should have a way to retrieve previous jobs after it does.

### Environment

- **Superstaq version**: N/A
- **general-superstaq version**: N/A
- **cirq-superstaq version**: N/A
- **qiskit-superstaq version**: '0.3.31'
- **Operating system**: Windows
- **Python version**: 3.9
- **Any other relevant dependencies**: 

### Any additional context?

Job retrieval appears to require the use of a private method.

**Comment by stephanielee9** [comment]
Have users pass in their fresh CQ token when they're getting the job

**Comment by vtomole** [comment]
Fixed by https://github.com/Infleqtion/client-superstaq/pull/708
