### ISSUE TITLE
ValueError from getting backends in qiskit-superstaq

### ISSUE THREAD

**Issue by ColinCampbellCQ** [Infleqtion/client-superstaq#622]
### What is happening?

Getting backends from a provider in qiskit-superstaq raises an exception because one of the backend names des not have a valid prefix.

![image](https://github.com/Infleqtion/client-superstaq/assets/108485140/f4ec8530-de92-48d3-be88-cab267363377)

### How can we reproduce the issue?

import qiskit_superstaq as qss
qss_provider = qss.superstaq_provider.SuperstaqProvider("token")
qss_provider.backends()

### What should happen?

A list of backends should be provided

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 0.4.3
- **Operating system**: 
- **Python version**: 
- **Any other relevant dependencies**: 

### Any additional context?

The NREL user did not have this problem, but I do not know if they have access to the same backends.

**Comment by vtomole** [comment]
This will be solved when you install the [latest version of qss](https://github.com/Infleqtion/client-superstaq/releases/tag/v0.4.4)

**Comment by ColinCampbellCQ** [comment]
Sorry! Resolved!
