### ISSUE TITLE
Supercheq tutorial missing link to environment variable information

### ISSUE THREAD

**Issue by epelaaez** [Infleqtion/client-superstaq#641]
### What is happening?

Documentation for Supercheq (https://superstaq.readthedocs.io/en/latest/apps/supercheq/Supercheq_css.html; notebook: https://github.com/Infleqtion/client-superstaq/blob/main/docs/source/apps/supercheq/Supercheq_css.ipynb; and same for qiskit-superstaq notebook) says:

> We then supply a Superstaq API token (or key) by either providing the API token as an argument of css.Service() or by setting it as an environment variable (see more details here).

But "here" at the end of this sentence does not link to anywhere.

### How can we reproduce the issue?

Look at documentation site or notebooks in this repo that generate it.

### What should happen?

"here" should link to somewhere, I'm not sure where.

### Environment

Latest.

**Comment by bharat-thotakura** [comment]
The hyperlink in ‘see more details [here](https://docs-superstaq.readthedocs.io/en/latest/get_started/basics.html#Set-up-access-to-Superstaq%E2%80%99s-API)’ for the optimization notebooks seems to be broken as well

**Comment by bharat-thotakura** [comment]
It should link here for the qiskit notebooks for example: https://superstaq.readthedocs.io/en/latest/get_started/basics/basics_qss.html#Set-up-access-to-Superstaq%E2%80%99s-API
