### ISSUE TITLE
Don't use `compile` as an option cause it's a python special function

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#642]
### What is happening?

Right now you can submit to Hilbert with `backend.run(circuit, shots, compile=False, route=False)` but, `compile=False` is setting 

Python's [compile](https://www.programiz.com/python-programming/methods/built-in/compile) to `False`

### How can we reproduce the issue?

```codeInString = 'a = 8\nb=7\nsum=a+b\nprint("sum =",sum)'
codeObject = compile(codeInString, 'sumstring', 'exec')

compile = False

codeObject = compile(codeInString, 'sumstring', 'exec')
```

Errors out

### What should happen?

Should pass. Maybe we should change the keyword arg to `transpile`?

### Environment

All up to date versions

**Comment by richrines1** [comment]
> Maybe we should change the keyword arg to `transpile`?

imo we should use "verbatim" (so `verbatim=True` would replace `compile=False`)
