### ISSUE TITLE
Job info populates after querying status

### ISSUE THREAD

**Issue by ColinCampbellCQ** [Infleqtion/client-superstaq#644]
### What is happening?

Jobs that have run on Hilbert appear to have no job info unless you query the job status with something like .result() or .status()

### How can we reproduce the issue?

`job = cq_hilbert_qpu.retrieve_job(job_id=job_id)`
`print(job._job_info)`
>>empty dictionary

`job = cq_hilbert_qpu.retrieve_job(job_id=job_id)`
`job.status()`
`print(job._job_info)`
>>populated dictionary

### What should happen?

The first dictionary should be populated

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 0.4.6
- **Operating system**: 
- **Python version**: 
- **Any other relevant dependencies**: 

### Any additional context?

This is not a problematic issue or a real bug. This is just something I noticed after being confused when looking at jobs after the fact.

**Comment by epelaaez** [comment]
@vtomole since `_job_info` is intended to be private, would the best solution for this be to add a `get_job_info` (or similar) method that looks into `_job_info` and if it is populated returns it and if not, it populates it and then returns it?

**Comment by vtomole** [comment]
@ColinCampbellCQ Thoughts on @epelaaez 's suggestion?

**Comment by ColinCampbellCQ** [comment]
I agree with @epelaaez. The best solution appears to be a simple `get_job_info` method that checks `_job_info`, populates it if needed, then returns `_job_info`.

**Comment by epelaaez** [comment]
I can work on implementing this tomorrow

**Comment by bharat-thotakura** [comment]
I think most of the information present in `_job_info` should already be accessible with some of the methods. For example, with `job.job_id`, `job.result()`, `job.compiled_circuits()`. Is there particular information that is present in `_job_info()` that is not accessible otherwise? I think we could then implement a specialized method for that info

**Comment by ColinCampbellCQ** [comment]
I guess not. The main motivator for my using _job_info was to access the circuit, but that was included in a recent release. There is pretty much only one other reason, which is that I think when I was using my cq_cloud token for submission, ._job_info would contain both my superstaq job id as well as my coldquanta cloud id. Having both of these is incredibly useful when talking with the hardware team because I need cloud job ids in order to work with them.

**Comment by bharat-thotakura** [comment]
I see, if I'm understanding this correctly, the goal then would be to store and more easily retrieve both the superstaq job id and the coldquanta cloud id associated with a job.

**Comment by ColinCampbellCQ** [comment]
I do believe that is an overarching goal; however, I think the process of getting those two things to work together nicely is of much greater scope than this issue. I think the get_job_info solution or the "do nothing because you can already get the information in other ways" solution are both perfectly fine for resolving the issue of getting the job info.

**Comment by bharat-thotakura** [comment]
I think having a nicely formatted get_job_info would be a good idea in the interim as the border issue is maybe tackled in a separate PR.

**Comment by richrines1** [comment]
imo this should be `job.to_dict()` instead of `job.get_job_info()` - ideally it \*shouldn't\* be returning any new/otherwise-inaccessible info about the job; it's just all the raw data making up this job in dictionary form
