### ISSUE TITLE
hash function used for github actions cache not being computed correctly

### ISSUE THREAD

**Issue by richrines1** [Infleqtion/client-superstaq#665]
### What is happening?

the hash is supposed to be generated from the contents of all `pyproject.toml` and `*requirements.txt` files in the repo. however "cirq-superstaq/example-requirements.txt" is changed in #664, but seems to be using the same hash as previous prs:

#636 (which doesn't change any requirements):
![image](https://github.com/Infleqtion/client-superstaq/assets/85512171/4edb02bd-594b-4a68-b9d5-a507cb75f48b)

#664 (which includes changes to `cirq-superstaq/example-requirements.txt`):
![image](https://github.com/Infleqtion/client-superstaq/assets/85512171/ca0d9cc4-98c2-49a6-baff-11ae62e7cdaf)

### How can we reproduce the issue?

see above

### What should happen?

the cache key should be different if the pr changes any requirements files

### Environment

- **client-superstaq version**: 0.4.8

**Comment by epelaaez** [comment]
In `ci.yml`, we do `hashFiles('**/pyproject.toml', '**requirements.txt')`. From the [documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#example-with-multiple-patterns), I think it should be `hashFiles('**/pyproject.toml', '**/requirements.txt')`. I'm not sure how to test if this fixes the issue though.

**Comment by richrines1** [comment]
> I think it should be `hashFiles('**/pyproject.toml', '**/requirements.txt')`

ah interesting. we also want it to match e.g. `cirq-superstaq/example-requirements.txt`, which i don't think this would - but maybe `hashFiles('**/pyproject.toml', '**/*requirements.txt')` would work? or if not we can try `hashFiles('**/pyproject.toml', '**/requirements.txt', '**/dev-requirements.txt', '**/example-requirements.txt')` 

> I'm not sure how to test if this fixes the issue though.

not sure if there's an easy way to check locally.. but if nothing else we can open a pr that just changes ci.yml, check the hash from the test logs, and then push the same change to cirq-superstaq/example-requirements.txt from #646 to see if the hash changes when we the checks rerun

**Comment by epelaaez** [comment]
It seems like the changes in https://github.com/Infleqtion/client-superstaq/pull/668 are working (using `**/*requirements.txt`). Hash before pushing the changes from #664 was:

<img width="599" alt="Screenshot 2023-07-31 at 11 55 30" src="https://github.com/Infleqtion/client-superstaq/assets/63567458/e321239b-6e50-4147-90c3-3fb7ab900f42">

(https://github.com/Infleqtion/client-superstaq/actions/runs/5717345651/job/15490882101)

and after merging those changes:

<img width="695" alt="Screenshot 2023-07-31 at 11 55 54" src="https://github.com/Infleqtion/client-superstaq/assets/63567458/d4c5f6c7-30f0-404c-9682-41efeee25f98">

(https://github.com/Infleqtion/client-superstaq/actions/runs/5717418586/job/15491120744)

**Comment by richrines1** [comment]
oh nice! let's merge #668 and close this then, and just keep an eye out for this in the future
