### ISSUE TITLE
Document `dry-run` in tutorials

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#696]
### What is happening?

Bennett from QuSTEAM tried to run the basics tutorial and got the following:
<img width="467" alt="image" src="https://github.com/Infleqtion/client-superstaq/assets/72408904/2aea4223-f3a1-4e31-b12a-4eadfd1d81db">

### How can we reproduce the issue?

Running the `qss` basics tutorial

### What should happen?

The user should get results

### Environment

Bennett was running the notebook in qBraid with the qiskit environment

**Comment by bharat-thotakura** [comment]
@stephanielee9 https://github.com/Infleqtion/client-superstaq/pull/698 should address the notebook issue.

**Comment by stephanielee9** [comment]
Thanks @bharat-thotakura! I'll close this once I get confirmation from Bennett that he's not having any other issues.

**Comment by stephanielee9** [comment]
Tutorial worked for Bennett
