### ISSUE TITLE
Some circuits should not run with `dry-run` and `verbatim=True`

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#712]
### What is happening?

Ran

```
qc = qiskit.QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])
qc.draw(output="mpl")
backend = provider.get_backend("ibmq_lagos_qpu")
job = backend.run(qc, method="dry-run", shots=100, verbatim=True)
result = job.result().get_counts()
```

And got counts back but this should perhaps not be able to run

### How can we reproduce the issue?

code above

### What should happen?

Error should be return to the user

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 0.4.14
- **Operating system**: MacOS
- **Python version**: 
- **Any other relevant dependencies**:

**Comment by richrines1** [comment]
i think this is because `verbatim` is currently ignored outside of `CQDevice`

**Comment by vtomole** [comment]
That's right. I'm working on a fix ATM.

**Comment by vtomole** [comment]
Related https://github.com/Infleqtion/server-superstaq/issues/884

**Comment by dowusu-antwi** [comment]
Why is it bad for `verbatim=True` and `method=dry-run` to return results? Doesn't it mean "don't compile this circuit" and "simulate it"?

(I think statevector simulation should give the same result whether or not you compile -- is this why?)

**Comment by richrines1** [comment]
i think the idea is that `method="dry-run"` should fail iff the same request would fail without dry-run - so if e.g. i pass `verbatim=True` but my circuit doesn't match the device graph, i should get an error whether or not i use dry-run

**Comment by stephanielee9** [comment]
@vtomole and @SalahedeenIssa to pair program on after Victory gets back from Munich

**Comment by stephanielee9** [comment]
@vtomole and @SalahedeenIssa to pair program Friday the 13th

**Comment by stephanielee9** [comment]
@vtomole and @SalahedeenIssa to sync offline for due dates (un-draft PR and review)

**Comment by stephanielee9** [comment]
@vtomole or @SalahedeenIssa: by Oct 27, can one of you comment with a timeline of when you expect the PR to be ready for review and a summary of what still needs to be done?

**Comment by SalahedeenIssa** [comment]
@vtomole and I pair programmed something last week but I think there were some bugs. I'll reach out to him to pair-program again this week

**Comment by vtomole** [comment]
@SalahedeenIssa I think we left of on you getting the checks to pass and addressing https://github.com/Infleqtion/server-superstaq/pull/2892/files#r1362672249 before we pair program again.

**Comment by vtomole** [comment]
@SalahedeenIssa is working on passing the checks then we'll pair program after that.

**Comment by stephanielee9** [comment]
@SalahedeenIssa - wanted to check if you had any updates for this issue this week or any questions on the review comments?

**Comment by vtomole** [comment]
@stephanielee9  Salahedeen's PR passes the checks. Me and @bharat-thotakura are reviewing now.
