### ISSUE TITLE
Add ACES notebook to readthedocs

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#721]
Same as [DFE](https://github.com/Infleqtion/client-superstaq/tree/main/docs/source/apps/dfe) but for ACES.

**Comment by epelaaez** [comment]
I think it would be worth waiting for https://github.com/quantumlib/Cirq/issues/6249 to be resolved so the tutorial can be made with more interesting noise models. This will also allow for a better theory/simulation comparison than using normal depolarizing channels.
