### ISSUE TITLE
Need a backend to retrieve an old job

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#727]
### What is happening?

Currently you need to define a backend to retrieve an old job (though the backend does not need to match the original backend the circuit was submitted on - I originally submitted on `ibmq_qasm_simulator`)

### How can we reproduce the issue?

<img width="745" alt="image" src="https://github.com/Infleqtion/client-superstaq/assets/72408904/e7f18757-af80-442b-83aa-d5fc70aac2d5">

### What should happen?

One way could be to retrieve the old job through provider instead of backend

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 0.4.14
- **Operating system**: MacOS
- **Python version**: 
- **Any other relevant dependencies**:

**Comment by vtomole** [comment]
>  retrieve the old job through provider instead of backend

Sounds good to me. Long term I think we need to phase out `backend`. This is justified given that qiskit is not 1.0 so we don't have to adhere to qiskit's UX.

**Comment by natibek** [comment]
@richrines1 are you still working on this? If not, I can help out.

**Comment by natibek** [comment]
@richrines1 would this be solved by the new interface?

**Comment by richrines1** [comment]
@natibek sorry missed this! honestly forgot about this issue, so definitely not working on it :) will assign you (i think we'll need the same thing regardless of any interface updates)

**Comment by bharat-thotakura** [comment]
Closing as addressed by #1099
