### ISSUE TITLE
`test_qudit_swap_gate` failure on MacOS 13.5.2

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#737]
### What is happening?

>       assert np.array_equal(
            cirq.Circuit(one_qb_gate0(q0), one_qb_gate1(q1), swap_op).unitary(),
            cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)).unitary(),
        )

<details>
E       AssertionError: assert False
E        +  where False = <function array_equal at 0x10ebc2330>(array([[ 0.60348044-0.22508465j,  0.14435176+0.20986404j,\n         0.53348885+0.40656493j, -0.10468142+0.24373003j],\n ...,\n       [ 0.03514636+0.26292064j,  0.62329721-0.24780231j,\n         0.19555466-0.16321372j, -0.52052528-0.37934834j]]), array([[ 0.60348044-0.22508465j,  0.14435176+0.20986404j,\n         0.53348885+0.40656493j, -0.10468142+0.24373003j],\n ...,\n       [ 0.03514636+0.26292064j,  0.62329721-0.24780231j,\n         0.19555466-0.16321372j, -0.52052528-0.37934834j]]))
E        +    where <function array_equal at 0x10ebc2330> = np.array_equal
E        +    and   array([[ 0.60348044-0.22508465j,  0.14435176+0.20986404j,\n         0.53348885+0.40656493j, -0.10468142+0.24373003j],\n ...,\n       [ 0.03514636+0.26292064j,  0.62329721-0.24780231j,\n         0.19555466-0.16321372j, -0.52052528-0.37934834j]]) = <bound method AbstractCircuit.unitary of cirq.Circuit([\n    cirq.Moment(\n        cirq.MatrixGate(np.array([[(-0.629153...ment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)),\n    ),\n])>()
E        +      where <bound method AbstractCircuit.unitary of cirq.Circuit([\n    cirq.Moment(\n        cirq.MatrixGate(np.array([[(-0.629153...ment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)),\n    ),\n])> = cirq.Circuit([\n    cirq.Moment(\n        cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432...oment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)),\n    ),\n]).unitary
E        +        where cirq.Circuit([\n    cirq.Moment(\n        cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432...oment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)),\n    ),\n]) = <class 'cirq.circuits.circuit.Circuit'>(cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0...6500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)), cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0....0766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(1, dimension=2)), css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)))
E        +          where <class 'cirq.circuits.circuit.Circuit'> = cirq.Circuit
E        +          and   cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0...6500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)) = cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0.5269677558306661+0.4925169106500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128')))(cirq.LineQid(0, dimension=2))
E        +          and   cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0....0766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(1, dimension=2)) = cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0.21329752190942666-0.29957810130766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128')))(cirq.LineQid(1, dimension=2))
E        +    and   array([[ 0.60348044-0.22508465j,  0.14435176+0.20986404j,\n         0.53348885+0.40656493j, -0.10468142+0.24373003j],\n ...,\n       [ 0.03514636+0.26292064j,  0.62329721-0.24780231j,\n         0.19555466-0.16321372j, -0.52052528-0.37934834j]]) = <bound method AbstractCircuit.unitary of cirq.Circuit([\n    cirq.Moment(\n        css.QuditSwapGate(dimension=2).on(cir...-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)),\n    ),\n])>()
E        +      where <bound method AbstractCircuit.unitary of cirq.Circuit([\n    cirq.Moment(\n        css.QuditSwapGate(dimension=2).on(cir...-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)),\n    ),\n])> = cirq.Circuit([\n    cirq.Moment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1...(-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)),\n    ),\n]).unitary
E        +        where cirq.Circuit([\n    cirq.Moment(\n        css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1...(-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)),\n    ),\n]) = <class 'cirq.circuits.circuit.Circuit'>(css.QuditSwapGate(dimension=2).on(cirq.LineQid(0, dimension=2), cirq.LineQid(1, dimension=2)), cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0...6500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(1, dimension=2)), cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0....0766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)))
E        +          where <class 'cirq.circuits.circuit.Circuit'> = cirq.Circuit
E        +          and   cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0...6500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(1, dimension=2)) = cirq.MatrixGate(np.array([[(-0.6291533287554012-0.289651801227836j), (-0.09432896225116162-0.7151013703259749j)], [(-0.5269677558306661+0.4925169106500402j), (0.6699545787473196+0.17576387414378794j)]], dtype=np.dtype('complex128')))(cirq.LineQid(1, dimension=2))
E        +          and   cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0....0766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128'))).on(cirq.LineQid(0, dimension=2)) = cirq.MatrixGate(np.array([[(-0.6555441396654814+0.6595597086802968j), (-0.3160240742135967-0.1880735392160327j)], [(0.21329752190942666-0.29957810130766077j), (-0.8659083911554541-0.3390572023873957j)]], dtype=np.dtype('complex128')))(cirq.LineQid(0, dimension=2))
</details>
### How can we reproduce the issue?

running `./check/pytest_.py cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py`

### What should happen?

tests pass with `np.allclose` instead of `np.array_equal`

### Environment

- **Superstaq version**: 
- **general-superstaq version**: 
- **cirq-superstaq version**: 
- **qiskit-superstaq version**: 
- **Operating system**: MacOS 13.5.2
- **Python version**: 3.11.2
- **Any other relevant dependencies**:

**Comment by vtomole** [comment]
What's the output of this script when you run it locally? I want to study the arrays are being reproduced by your machine.

```python
import cirq
import cirq_superstaq as css
from cirq._compat import proper_repr

q0, q1 = cirq.LineQid.range(2, dimension=2)
swap_op = css.QuditSwapGate(dimension=2).on(q0, q1)
one_qb_gate0 = cirq.MatrixGate(cirq.testing.random_unitary(2,), qid_shape=(2,),)
one_qb_gate1 = cirq.MatrixGate(cirq.testing.random_unitary(2,), qid_shape=(2,),)

print(proper_repr(cirq.unitary(cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)))))
print("\n")
print(proper_repr(cirq.unitary(cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)))))
```

**Comment by stephanielee9** [comment]
```
import cirq
   ...: import cirq_superstaq as css
   ...: from cirq._compat import proper_repr
   ...: 
   ...: q0, q1 = cirq.LineQid.range(2, dimension=2)
   ...: swap_op = css.QuditSwapGate(dimension=2).on(q0, q1)
   ...: one_qb_gate0 = cirq.MatrixGate(cirq.testing.random_unitary(2,), qid_shape=(2,),)
   ...: one_qb_gate1 = cirq.MatrixGate(cirq.testing.random_unitary(2,), qid_shape=(2,),)
   ...: 
   ...: print(proper_repr(cirq.unitary(cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)))))
   ...: print("\n")
   ...: print(proper_repr(cirq.unitary(cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)))))
np.array([[(-0.40753411930224936+0.14656980112152498j), (0.0867833126582587-0.16922018977903477j), (-0.3178966707184036-0.7414335294243184j), (0.32430234895049675+0.14252169545611937j)], [(0.5541643801142261-0.5862455216213273j), (-0.001981183688061657+0.3542322996589819j), (-0.331950239352958-0.2781650653654719j), (0.18989636319999462-0.010304718735091116j)], [(0.0515409120679696+0.1830583250442203j), (0.37042206333423267+0.22439754898722336j), (-0.3346326188398712+0.11621298386525483j), (-0.3759956576792797+0.7137291063245026j)], [(-0.23957041434792778-0.2609414949364295j), (-0.8043580297510406-0.06156404619151599j), (-0.13215110931729798+0.13675854741478186j), (-0.007182272173894356+0.4330302298485449j)]], dtype=np.dtype('complex128'))


np.array([[(-0.40753411930224936+0.14656980112152498j), (0.0867833126582587-0.16922018977903477j), (-0.3178966707184036-0.7414335294243184j), (0.32430234895049675+0.14252169545611937j)], [(0.5541643801142261-0.5862455216213273j), (-0.001981183688061657+0.3542322996589819j), (-0.331950239352958-0.2781650653654719j), (0.18989636319999462-0.010304718735091116j)], [(0.0515409120679696+0.1830583250442203j), (0.37042206333423267+0.22439754898722336j), (-0.3346326188398712+0.11621298386525483j), (-0.3759956576792797+0.7137291063245026j)], [(-0.23957041434792778-0.2609414949364295j), (-0.8043580297510406-0.06156404619151599j), (-0.13215110931729798+0.13675854741478186j), (-0.007182272173894356+0.4330302298485449j)]], dtype=np.dtype('complex128'))
```

**Comment by vtomole** [comment]
How about `print(proper_repr(cirq.unitary( cirq.Circuit(one_qb_gate0(q0), one_qb_gate1(q1), swap_op))))`?

**Comment by stephanielee9** [comment]
`np.array([[(0.14564720370854106-0.18887544450748314j), (0.005322904169673237-0.3772391232476945j), (-0.47796460416680586+0.014313029369022798j), (-0.5915948719621779+0.4713127951992173j)], [(0.4177325171740395-0.23271134424752649j), (0.30825489484125923-0.690723651873055j), (0.2218734662335126+0.08751689246964217j), (0.36390167103910587-0.09956537165317589j)], [(-0.33046946223987395-0.18200995561885414j), (0.23619806015474018-0.033128807179769536j), (0.13794163892673228+0.7437017868074891j), (-0.3516256109916801-0.32405933922782976j)], [(-0.46478212226371457-0.5967393252287656j), (0.46132416576590973+0.12583735425714196j), (0.08316104154169737-0.36799718828706923j), (0.09736988314279928+0.21772952795331685j)]], dtype=np.dtype('complex128'))`

**Comment by vtomole** [comment]
:thinking:  

How about

```python
a =  cirq.unitary(cirq.Circuit(one_qb_gate0(q0), one_qb_gate1(q1), swap_op))
b =  cirq.unitary(cirq.Circuit(swap_op, one_qb_gate0(q1), one_qb_gate1(q0)))

print(proper_repr(a))
print("\n")
print(proper_repr(b))
print(np.array_equal(a, b))
```

**Comment by stephanielee9** [comment]
```
np.array([[(0.14564720370854106-0.18887544450748314j), (0.005322904169673239-0.3772391232476945j), (-0.47796460416680586+0.01431302936902279j), (-0.5915948719621779+0.47131279519921737j)], [(0.4177325171740395-0.23271134424752649j), (0.30825489484125923-0.690723651873055j), (0.2218734662335126+0.08751689246964217j), (0.36390167103910587-0.09956537165317589j)], [(-0.33046946223987395-0.18200995561885414j), (0.23619806015474018-0.03312880717976954j), (0.1379416389267323+0.7437017868074891j), (-0.3516256109916801-0.32405933922782976j)], [(-0.4647821222637146-0.5967393252287656j), (0.46132416576590973+0.12583735425714196j), (0.08316104154169737-0.36799718828706923j), (0.09736988314279928+0.21772952795331685j)]], dtype=np.dtype('complex128'))


np.array([[(0.14564720370854106-0.18887544450748314j), (0.005322904169673239-0.3772391232476945j), (-0.47796460416680586+0.014313029369022798j), (-0.5915948719621779+0.47131279519921737j)], [(0.4177325171740395-0.23271134424752649j), (0.30825489484125923-0.690723651873055j), (0.2218734662335126+0.08751689246964217j), (0.36390167103910587-0.09956537165317589j)], [(-0.33046946223987395-0.18200995561885414j), (0.23619806015474018-0.03312880717976954j), (0.1379416389267323+0.7437017868074891j), (-0.3516256109916801-0.32405933922782976j)], [(-0.4647821222637146-0.5967393252287656j), (0.46132416576590973+0.12583735425714196j), (0.08316104154169737-0.36799718828706923j), (0.09736988314279928+0.21772952795331685j)]], dtype=np.dtype('complex128'))
False
```
