### ISSUE TITLE
`provider.backends()` is too slow

### ISSUE THREAD

**Issue by richrines1** [Infleqtion/client-superstaq#772]
### What is happening?

running `provider.backends()` is taking 45-60s to complete. About 15s of this is the time it takes to get the list of targets (and so this is about how long `css.Service().get_targets()` takes), The remaining 30s is just due to the calls to `target_info` for each backend

imo we should be returning more info from the get_targets endpoint to obviate the need for all the subsequent target_info calls, and anything not returned as part of `get_targets` should be lazily retrieved by backends if necessary

### How can we reproduce the issue?

```python
provider = qss.SuperstaqProvider()
service = css.Service()

t0 = time.time()
_ = provider.backends()
t1 = time.time()
_ = service.get_targets()
t2 = time.time()

print("provider.get_backends():", t1 - t0)
print("service.get_targets():", t2 - t1)
```
which just gave me
```
provider.get_backends(): 44.30445456504822
service.get_targets(): 14.650813341140747
```

### What should happen?

provider.backends() shouldn't take much longer than service.get_targets(), or about 15s (ideally both should be faster)

### Environment

- **Superstaq version**: 0.4.37
- **client-superstaq version**: 0.4.22

**Comment by paaige** [comment]
provider.backends has the following extra code (vs service.get_targets):
`targets = self._client.get_targets()["superstaq_targets"]
        backends = []
        for target in targets["compile-and-run"]:
            backends.append(self.get_backend(target))`
i assume the targets in `targets["compile-and-run"]`should already be included in `superstaq_targets`.

**Comment by richrines1** [comment]
^ so i think this actually brings up an unrelated issue: now that `compile()` is part of `SuperstaqBackend`, `provider.get_backends()` shouldn't be limited to just compile-and-run targets

i think the ideal way to fix the performance issue would be to:
1. complete https://github.com/Infleqtion/server-superstaq/issues/2813 so we get more information from `get_targets()`
2. allow this information to be used when constructing `SuperstaqBackend` objects (e.g. with a `SuperstaqBackend.from_dict` classmethod)
3. if constructed in this way, defer the `target_info()` call to whenever the info is actually needed (instead of putting it in `backend.__init__`)
