### ISSUE TITLE
version conflicts when installing checks-superstaq and cirq-superstaq in series

### ISSUE THREAD

**Issue by perlinm** [Infleqtion/client-superstaq#832]
### What is happening?

I get a pip warning when trying to install `checks-superstaq` and `cirq-superstaq` in series from a fresh environment:
```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
referencing 0.30.2 requires attrs>=22.2.0, but you have attrs 21.4.0 which is incompatible.
```

### How can we reproduce the issue?

From a fresh python environment:
```bash
pip install checks-superstaq
pip install cirq-superstaq
```
This command ends with the above pip error, after which
```shell
$ pip check
referencing 0.30.2 has requirement attrs>=22.2.0, but you have attrs 21.4.0.
```

NOTE: there is NO ERROR if I instead run
```bash
pip install checks-superstaq cirq-superstaq
```
so we can plausibly declare this to be an issue with `pip`...

### What should happen?

Everything should install without version conflicts

### Environment

Fresh (empty) conda environment:
```bash
conda create --name test python=3.11
conda activate test
```

**Comment by richrines1** [comment]
i think this is due to a downstream dependency of `cirq-rigetti` - hotfix is to pin
```
jsonschema~=4.17.3
```
to checks-superstaq/requirements.txt

**Comment by perlinm** [comment]
Confirming that this pin does indeed solve the problem.  Should we add it?  Or just let the problem fix itself on the `cirq-rigetti` end?

**Comment by bharat-thotakura** [comment]
With https://github.com/Infleqtion/client-superstaq/pull/883, `cirq-superstaq` has no dependency on `cirq-rigetti` (by only requiring `cirq-core`) so it seems this is no longer an issue.
