### ISSUE TITLE
Discussion: Parallelism SupermarQ Metric

### ISSUE THREAD

**Issue by burgholzer** [Infleqtion/client-superstaq#895]
Unfortunately, this repository does not have discussions enabled because this is neither a feature request nor a bug report.
The point of discussion is the implementation of the parallelism SupermarQ metric:

https://github.com/Infleqtion/client-superstaq/blob/91d947f8cc1d99f90dca58df5248d9016e4a5345/supermarq-benchmarks/supermarq/converters.py#L71-L84

The definition being used in the code significantly differs from the one used in https://arxiv.org/abs/2202.11045, which roughly corresponds to the following pseudo code
```python
((n_g / d) - 1) / (n - 1)
```
with `n_g` being the number of gates, `d` the circuit depth, and `n` the number of qubits.

Some observations:
- While the metric from the paper depends on the number of qubits, the metric in the code does not. This leads to a situation where the paper metric would yield the same value for, e.g., a Hadamard cascade on `n` qubits independent of `n`, but the new metric yields a value that decreases with increasing `n`
- The metric from the paper is not well defined for a single qubit, but presumably the parallelism would/should be `0` in that case, right?
- While it is possible to achieve `parallelism==1.` for a non-empty circuit using the metric from the paper (`d==1`, `n_g==n`), this is no longer possible for the metric in the code since this can only ever happen if either the depth is zero (contradicting the circuit to be non-empty).

It would be much appreciated if you could briefly comment on the above.

**Comment by teaguetomesh** [comment]
Hi @burgholzer, thanks for taking the time to point this out. I think your observations all make quite a lot of sense, and I can't recall or find why the current metric in the code is defined the way it is. 

I think it'd make the most sense here to update the code to match the specification in the paper. Would you care to open a PR?

**Comment by burgholzer** [comment]
Hey 👋🏻 

Sure. I'll create one once I am back from my short vacation.
