### ISSUE TITLE
AttributeError: module 'cirq_superstaq' has no attribute 'SuperstaqProvider'

### ISSUE THREAD

**Issue by vandnaChaturvedi** [Infleqtion/client-superstaq#951]
### What is happening?

while declaring the Superstaq API token in the code, 
 > provider = cirq_superstaq.SuperstaqProvider(<token>)
getting error  --   
>  AttributeError: module 'cirq_superstaq' has no attribute 'SuperstaqProvider'
![2024-May-20_Mon_14 47](https://github.com/Infleqtion/client-superstaq/assets/30197493/8211b691-cec6-4cd4-8029-c25e47e7fd0a)

### How can we reproduce the issue?

 import qiskit
 import qiskit_superstaq as qss
 import supermarq 
import collections
from supermarq.benchmarks.ghz import GHZ
import cirq
import os  
import cirq_superstaq

nq = 3
ghz = sm.benchmarks.ghz.GHZ(nq)
print(ghz.circuit())
> provider = cirq_superstaq.SuperstaqProvider("<token>")

### What should happen?

provider variable should be ready with the cirq compiler, to execute the code.

### Environment

- **Superstaq version**:  Not installed
- **general-superstaq version**:  0.5.15
- **cirq-superstaq version**:  0.1.31
- **qiskit-superstaq version**: 0.1.24
- **Operating system**: Linux Ubuntu 22.04.4 LTS
- **Python version**: Python 3.8.19
- **SupermarQ**: 0.0.3

**Comment by vtomole** [comment]
Hi @vandnaChaturvedi,

`SuperstaqProvider` is part of qiskit. `provider = qss.SuperstaqProvider("")` will work.
