### ISSUE TITLE
add --disable-socket to setup.cfg after next release of pytest-socket 

### ISSUE THREAD

**Issue by spencerdearman** [Infleqtion/client-superstaq#962]
Currently we pass --disable-socket to pytest in pytest_.py and coverage_.py. The next version of pytest-socket will fix this by adding https://github.com/miketheman/pytest-socket/pull/186 to override the config file, so once that's released we should use it

**Comment by vtomole** [comment]
You want to link to the existing issue https://github.com/Infleqtion/client-superstaq/issues/962
